keys:
  # Users
  - &users:
    - &leo BB6CEB57452F6236BA0001D7274249FAF8F3F735
  # Hosts
  - &hosts:
    - &surface age1z9r9kqlpwlh4qf0j05nfryylph2a3p2k3f8af8gs096ahe3jm4eqt9c9s9

creation_rules:
  - path_regex: hosts/taygeta/secrets.ya?ml$
    key_groups:
    - age:
      - *surface
      pgp:
      - *leo

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *surface
      pgp:
      - *leo
