keys:
  # Users
  - &users:
    - &leo BB6CEB57452F6236BA0001D7274249FAF8F3F735
  # Hosts
  - &hosts:
    - &surface age1hm5lf4qk84r4wh00atn6hpts7mpdx80adq26wht2e5qh9ewvhyaszfv82d

creation_rules:
  - path_regex: hosts/taygeta/secrets.ya?ml$
    key_groups:
    - age:
      - *surface
      pgp:
      - *leo

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *surface
      pgp:
      - *leo
